sudo: required
serices:
  - docker


before_install:
  docker build -t umernisar/travis-react -f Dockerfile.dev .

script:
  docker run -e CI=true umernisar/travis-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  username: "$dock-react"
  password: "d22dZeaokHWp11kMTeKYi1xrh3eEoNsRJXNHrX8io0qdjtZPTbLjoNWhidF5"
  site: "dock-react"